### ISSUE TITLE
Gitlab API Token - Error PKIX

### ISSUE THREAD

**Issue by fabianolc** [Blarc/gitlab-template-lint-plugin#106]
How can I disable certificate verification?

![gitlab](https://user-images.githubusercontent.com/1316748/234026843-a4d65a28-ae24-4e65-9d8b-943342dcc688.png)

**Comment by Blarc** [comment]
Also, check this issue: https://github.com/Blarc/gitlab-template-lint-plugin/issues/39.

**Comment by K2ouMais** [comment]
I am having the same problems... This plugin is really a nightmare to configure.

I have imported the company certificates, added a token with access to api and api_read and I get exactly the same error like on the first post.

I think I am going to give up on this 😢

**Comment by Blarc** [comment]
Hey @K2ouMais,

I'm sorry to hear you have problems configuring the plugin. Most of the configuration should be set automatically with the exception of the personal access token.

Regarding the certificate, have you tried https://github.com/Blarc/gitlab-template-lint-plugin/issues/39#issuecomment-1329386919 ?

**Comment by Blarc** [comment]
@K2ouMais I have added a setting for allowing self-signed certificate. Can you please download the new version of the plugin here: https://github.com/Blarc/gitlab-template-lint-plugin/suites/12517754559/artifacts/668085913, install it by following the [steps](https://github.com/Blarc/gitlab-template-lint-plugin#installation-from-zip) and report back if this solves the problem? :pray:

**Comment by K2ouMais** [comment]
The version 1.9 seems to work without a problem 👍🏻

**Comment by evsmorodin** [comment]
Hello! I have a same issue

PhpStorm 2023.1.2
Gitlab Template Lint 1.13.0
