### ISSUE TITLE
Gitlab url and token for all projects

### ISSUE THREAD

**Issue by henryh** [Blarc/gitlab-template-lint-plugin#112]
Hello! Thank you for the plugin!
I have a gitlab at gitlab.myurl.com and I would like to make a common configuration for all projects. But the configuration is only used for the current project. How to make a global configuration?
<img width="611" alt="Screenshot 2023-04-27 at 11 02 48 AM" src="https://user-images.githubusercontent.com/19281673/234799347-b2627d86-cec0-4c06-a951-d26e1de5c9de.png">

**Comment by Blarc** [comment]
Hi. Once you set a Gitlab API token for a Gitlab API URL, that token is automatically used for all repositories that are hosted on that Gitlab. The Gitlab API URL should be automatically computed from the current git repository, but can also be set in the Remotes table:
![image](https://user-images.githubusercontent.com/36704759/234801322-6b68b6f7-42dc-49be-83bf-08c8e436a204.png)

**Comment by henryh** [comment]
Not working :( May be because I can't change the API server in the Remotes
<img width="695" alt="Screenshot 2023-04-27 at 4 16 07 PM" src="https://user-images.githubusercontent.com/19281673/234873682-84263a92-ebf7-4e7b-a816-5054d3d9e846.png">

I have different url for the api and the repository, and the plugin use only a parsed url

**Comment by Blarc** [comment]
Aha okay. I've noticed that myself, but didn't think it would a problem. I think I only show the gitlab urls that were recognized for current project in the combo box.

Will change this, so all gitlab urls are showed and you will able to pick a different one in the combo box. 

Thanks for making the issue 🙏

**Comment by Blarc** [comment]
This change is released under version 1.11.0. You can wait for JetBrains to approve version 1.11.0 or download it manually from https://github.com/Blarc/gitlab-template-lint-plugin/releases/tag/v1.11.0 and installing it following these [steps](https://github.com/Blarc/gitlab-template-lint-plugin#installation-from-zip).

Thanks for reporting back. :raised_hands:
