### ISSUE TITLE
WorkspaceFileIndex is not initialized yet

### ISSUE THREAD

**Issue by mgrundkoetter** [Blarc/gitlab-template-lint-plugin#117]
I use:
PhpStorm 2023.1.1 Build #PS-231.8770.68
Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
on macOS 13.1
and the IDE shows an internal error with the following stacktrace:

**java.lang.Throwable: WorkspaceFileIndex is not initialized yet, empty data is returned. Activities which use the project configuration must be postponed until the project is fully loaded.**
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
> 	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getMainIndexData(WorkspaceFileIndexImpl.kt:261)
> 	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getOrCreateIndexData(WorkspaceFileIndexImpl.kt:253)
> 	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
> 	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isUnderIgnored(ProjectFileIndexImpl.java:99)
> 	at com.intellij.openapi.roots.impl.ProjectFileIndexFacade.isUnderIgnored(ProjectFileIndexFacade.java:66)
> 	at com.intellij.psi.impl.file.impl.FileManagerImpl.isExcludedOrIgnored(FileManagerImpl.java:425)
> 	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:411)
> 	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:403)
> 	at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:169)
> 	at com.intellij.psi.AbstractFileViewProvider.shouldCreatePsi(AbstractFileViewProvider.java:86)
> 	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.getPsiInner(MultiplePsiFilesPerDocumentFileViewProvider.java:82)
> 	at com.intellij.psi.AbstractFileViewProvider.getPsi(AbstractFileViewProvider.java:190)
> 	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:363)
> 	at com.intellij.psi.impl.PsiDocumentManagerBase.getPsiFile(PsiDocumentManagerBase.java:148)
> 	at com.intellij.psi.impl.PsiDocumentManagerBase.getPsiFile(PsiDocumentManagerBase.java:97)
> 	at com.intellij.psi.impl.PsiDocumentManagerImpl.getPsiFile(PsiDocumentManagerImpl.java:64)
> 	at com.github.blarc.gitlab.template.lint.plugin.listeners.SaveActionListener.beforeDocumentSaving(SaveActionListener.kt:14)
> 	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:680)
> 	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:640)
> 	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:482)
> 	at com.intellij.util.messages.impl.ToDirectChildrenMessagePublisher.publish$intellij_platform_core(CompositeMessageBus.kt:294)
> 	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:442)
> 	at jdk.proxy1/jdk.proxy1.$Proxy28.beforeDocumentSaving(Unknown Source)
> 	at jdk.internal.reflect.GeneratedMethodAccessor931.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:172)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$new$0(FileDocumentManagerImpl.java:127)
> 	at jdk.proxy1/jdk.proxy1.$Proxy28.beforeDocumentSaving(Unknown Source)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocumentInWriteAction$4(FileDocumentManagerImpl.java:413)
> 	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:326)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocumentInWriteAction(FileDocumentManagerImpl.java:412)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocument$2(FileDocumentManagerImpl.java:373)
> 	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:87)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:946)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:972)
> 	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:86)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocument(FileDocumentManagerImpl.java:373)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocuments(FileDocumentManagerImpl.java:291)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:266)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:259)
> 	at com.intellij.openapi.externalSystem.autoimport.ProjectSettingsTracker$submitSettingsFilesRefresh$2.invoke(ProjectSettingsTracker.kt:165)
> 	at com.intellij.openapi.externalSystem.autoimport.ProjectSettingsTracker$submitSettingsFilesRefresh$2.invoke(ProjectSettingsTracker.kt:163)
> 	at com.intellij.openapi.externalSystem.autoimport.settings.EdtAsyncSupplier.supply$lambda$0(EdtAsyncSupplier.kt:16)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
> 	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
> 	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
> 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
> 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
> 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
> 	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
> 	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
> 	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
>

**Comment by Blarc** [comment]
Does this happen on start up?

**Comment by mgrundkoetter** [comment]
The error occurred after I opened the project, yes.

**Comment by Blarc** [comment]
Thank you, will look into it.

**Comment by Blarc** [comment]
A fix was released under version 1.11.1. You can wait for JetBrains to approve version 1.11.1 or download it manually from https://github.com/Blarc/gitlab-template-lint-plugin/releases/tag/v1.11.1 and installing it following these [steps](https://github.com/Blarc/gitlab-template-lint-plugin#installation-from-zip).

Thanks for reporting back. :raised_hands:
