### ISSUE TITLE
GitLab API url changes to invalid for project cloned with SSH

### ISSUE THREAD

**Issue by adesko** [Blarc/gitlab-template-lint-plugin#194]
I have a repository that's cloned with SSH (so the clone link looks like ssh://git@ssh.mygitlab.com:8888/group/project.git)
I manually add the Gitlab API url (https://mygitlab.com/api/v4) and token and it validates successfully.
But when i try to lint something, it removes my saved api url and adds a new api url to https://ssh.mygitlab.com/api/v4 without a token.
I would like it to not auto-change the api url i manually entered, saved and set as the projects origin/api url

**Comment by Blarc** [comment]
Hey @adesko,

that's a very interesting remote url :smiley: . I also use ssh for cloning and this is how mine looks: `git@gitlab.medius.si:medius/ci-tools/medius-cd.git`.

If you go to `Tools > Gitlab Template Lint > Remotes`, you should be able to see Gitlab API URL for each recognised remote. In this table you should see you remote URL and you can set the corresponding Gitlab API URL.

![gitlabtemplatlint](https://github.com/Blarc/gitlab-template-lint-plugin/assets/36704759/067096ac-a8b0-4253-9f1b-1172d610ec38)

**Comment by adesko** [comment]
@Blarc thanks, i think i figured it out... had to add another remote since the one on ssh didn't have https enabled on the domain and was failing all requests
